name: health_food_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: 
  jiffy: 
  intl: 
  http: 
  cached_network_image:  
  image_picker: 
  show_up_animation: 
  auto_animated:  
  flutter_local_notifications: 
  cloud_firestore: 
  flutter_svg: 
  font_awesome_flutter: 
  fluttericon:   
  device_preview: 
  responsive_builder: 
  image_pickers:
  email_auth:  
  file_picker:
  email_otp:
    
  




  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
   - assets/images/
  #  - images/a_dot_ham.jpeg
  fonts:
    - family: Montaga
      fonts:
        - asset: assets/fonts/Montaga-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
